"""normalize school relations

Revision ID: 1f53e9ecf457
Revises: ff1544c99750
Create Date: 2026-05-26 05:34:39.715548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f53e9ecf457'
down_revision: Union[str, Sequence[str], None] = 'ff1544c99750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_attendance_date'), table_name='attendance_records')
    op.drop_index(op.f('idx_attendance_section'), table_name='attendance_records')
    op.drop_index(op.f('idx_attendance_student'), table_name='attendance_records')
    op.drop_constraint(op.f('attendance_records_section_id_fkey'), 'attendance_records', type_='foreignkey')
    op.drop_column('attendance_records', 'section_id')
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('classrooms', 'is_active')
    op.drop_column('classrooms', 'display_order')
    # Step 1: add nullable first
    op.add_column(
        "parents",
        sa.Column(
            "full_name",
            sa.String(100),
            nullable=True,
        )
    )

    # Step 2: migrate existing data
    op.execute(
        """
        UPDATE parents
        SET full_name =
            COALESCE(
                father_name,
                guardian_name,
                'Unknown Parent'
            )
        """
    )

    # Step 3: make required after data exists
    op.alter_column(
        "parents",
        "full_name",
        nullable=False,
    )
    op.alter_column('parents', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('parents', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('parents', 'mother_name')
    op.drop_column('parents', 'occupation')
    op.drop_column('parents', 'address')
    op.drop_column('parents', 'is_active')
    op.drop_column('parents', 'guardian_name')
    op.drop_column('parents', 'father_name')
    op.drop_column('parents', 'alternate_mobile_number')
    op.alter_column('sections', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_column('sections', 'capacity')
    op.drop_column('sections', 'is_active')
    op.drop_column('sections', 'display_order')
    op.alter_column('student_parent_mappings', 'relationship_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('students', 'admission_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('students', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('students_academic_year_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('students_classroom_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'roll_number')
    op.drop_column('students', 'mobile_number')
    op.drop_column('students', 'academic_year_id')
    op.drop_column('students', 'guardian_mobile_number')
    op.drop_column('students', 'address')
    op.drop_column('students', 'classroom_id')
    op.drop_column('students', 'admission_date')
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'guardian_name')
    op.drop_column('students', 'email')
    op.drop_column('teacher_section_mappings', 'is_class_teacher')
    op.alter_column('teachers', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('teachers', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('teachers_employee_id_key'), 'teachers', type_='unique')
    op.drop_column('teachers', 'experience_years')
    op.drop_column('teachers', 'qualification')
    op.drop_column('teachers', 'is_active')
    op.drop_column('teachers', 'joining_date')
    op.drop_column('teachers', 'is_class_teacher')
    op.drop_column('teachers', 'employee_id')
    op.drop_column('teachers', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('is_class_teacher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('qualification', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('teachers_employee_id_key'), 'teachers', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('teachers', 'mobile_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('teachers', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.add_column('teacher_section_mappings', sa.Column('is_class_teacher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('guardian_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('admission_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('classroom_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('guardian_mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('academic_year_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('roll_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('students_classroom_id_fkey'), 'students', 'classrooms', ['classroom_id'], ['id'])
    op.create_foreign_key(op.f('students_academic_year_id_fkey'), 'students', 'academic_years', ['academic_year_id'], ['id'])
    op.alter_column('students', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('students', 'admission_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('student_parent_mappings', 'relationship_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('sections', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sections', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('sections', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('sections', 'name',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('parents', sa.Column('alternate_mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('parents', sa.Column('father_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('parents', sa.Column('guardian_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('parents', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('parents', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('parents', sa.Column('occupation', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('parents', sa.Column('mother_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.alter_column('parents', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('parents', 'mobile_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('parents', 'full_name')
    op.add_column('classrooms', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('classrooms', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('classrooms', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('attendance_records', sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('attendance_records_section_id_fkey'), 'attendance_records', 'sections', ['section_id'], ['id'])
    op.create_index(op.f('idx_attendance_student'), 'attendance_records', ['student_id'], unique=False)
    op.create_index(op.f('idx_attendance_section'), 'attendance_records', ['section_id'], unique=False)
    op.create_index(op.f('idx_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    # ### end Alembic commands ###
