"""add student parent constraints

Revision ID: 4039a0c46786
Revises: edb8e7e05e2a
Create Date: 2026-06-01 09:02:33.322435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4039a0c46786'
down_revision: Union[str, Sequence[str], None] = 'edb8e7e05e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_relationship_type', 'student_parent_mappings', ['student_id', 'relationship_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_relationship_type', 'student_parent_mappings', type_='unique')
    # ### end Alembic commands ###
