"""create homepage widgets table

Revision ID: 6ca1b785db01
Revises: 1adf9bb84f85
Create Date: 2026-05-21 17:57:34.404470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca1b785db01'
down_revision: Union[str, Sequence[str], None] = '1adf9bb84f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_widgets',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('redirect_url', sa.String(length=1000), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('visibility_roles', sa.JSON(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attendance_date', 'attendance_records', ['attendance_date'], unique=False)
    op.create_index('idx_attendance_section', 'attendance_records', ['section_id'], unique=False)
    op.create_index('idx_attendance_student', 'attendance_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attendance_student', table_name='attendance_records')
    op.drop_index('idx_attendance_section', table_name='attendance_records')
    op.drop_index('idx_attendance_date', table_name='attendance_records')
    op.drop_table('homepage_widgets')
    # ### end Alembic commands ###
