"""added tagline column in settings table

Revision ID: 7a00c81eaa51
Revises: 6ca1b785db01
Create Date: 2026-05-22 04:26:13.689534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a00c81eaa51'
down_revision: Union[str, Sequence[str], None] = '6ca1b785db01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_settings', sa.Column('tag_line', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_settings', 'tag_line')
    # ### end Alembic commands ###
