"""update school settings columns

Revision ID: af2a1a8fca09
Revises: 3151b4f52088
Create Date: 2026-05-19 09:24:17.164931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af2a1a8fca09'
down_revision: Union[str, Sequence[str], None] = '3151b4f52088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_settings', sa.Column('secondary_color', sa.String(length=20), nullable=True))
    op.add_column('school_settings', sa.Column('welcome_screen', sa.JSON(), nullable=True))
    op.add_column('school_settings', sa.Column('login_screen', sa.JSON(), nullable=True))
    op.add_column('school_settings', sa.Column('features_enabled', sa.JSON(), nullable=True))
    op.drop_column('school_settings', 'feature_flags_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_settings', sa.Column('feature_flags_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('school_settings', 'features_enabled')
    op.drop_column('school_settings', 'login_screen')
    op.drop_column('school_settings', 'welcome_screen')
    op.drop_column('school_settings', 'secondary_color')
    # ### end Alembic commands ###
