"""update homepage jsonb fields new

Revision ID: ff1544c99750
Revises: 8117e8382963
Create Date: 2026-05-25 13:25:45.646178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1544c99750'
down_revision: Union[str, Sequence[str], None] = '8117e8382963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homepage_items', 'image_url')
    op.drop_column('homepage_items', 'subtitle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homepage_items', sa.Column('subtitle', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('homepage_items', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
